// Twilit Dawn: Twilit Essentials, Dawnlight and A Link Between Twilight compiled into one mod.
// This file owns the mod definition and entry points. overlaps.cpp keeps features the mods share to
// one owner; settings_hub.cpp shows all their settings in one window.

#include "mods/service.hpp"
#include "imports.inc"  // generated by update.py: SDK headers, DEFINE_MOD and all three mods' imports

#include "twilit.hpp"

#include "collection_lib/custom_equip.hpp"

#include <iterator>
#include <string>

extern "C" {
ModResult essentials_mod_initialize(ModError* error);
ModResult essentials_mod_update(ModError* error);
ModResult essentials_mod_shutdown(ModError* error);
ModResult dawnlight_mod_initialize(ModError* error);
ModResult dawnlight_mod_update(ModError* error);
ModResult dawnlight_mod_shutdown(ModError* error);
ModResult albw_mod_initialize(ModError* error);
ModResult albw_mod_update(ModError* error);
ModResult albw_mod_shutdown(ModError* error);
}

namespace dawnlight {
// Written by Dawnlight's config; its updater (the only reader) is left out of Twilit Dawn.
bool g_configCheckForUpdatesEnabled = false;
}  // namespace dawnlight

// ALBW is about to change Link's outfit (update.py hooks its equip and rental paths): take off
// Essentials' custom tunic first, as picking a vanilla tunic in Essentials' Collection does, or
// Essentials would force it back every frame and the ALBW outfit would never load.
void twilit_albw_outfit_changing() {
    if (custom_equip_active(CE_TUNIC)) custom_equip_clear(CE_TUNIC);
}

namespace {

struct Part {
    const char* name;
    ModResult (*initialize)(ModError*);
    ModResult (*update)(ModError*);
    ModResult (*shutdown)(ModError*);
};

// Init order matters: Dawnlight settles Z-slot/stamina ownership against Essentials before it
// installs its hooks (see twilit_dawn_resolve_conflicts).
const Part kParts[] = {
    {"Twilit Essentials", essentials_mod_initialize, essentials_mod_update, essentials_mod_shutdown},
    {"Dawnlight", dawnlight_mod_initialize, dawnlight_mod_update, dawnlight_mod_shutdown},
    {"A Link Between Twilight", albw_mod_initialize, albw_mod_update, albw_mod_shutdown},
};

void undo(size_t initialized) {
    while (initialized-- > 0) {
        const TwilitPartScope scope(static_cast<int>(initialized));
        kParts[initialized].shutdown(nullptr);
    }
    settings_hub_shutdown();
    twilit_config_uninstall();
    twilit_hooks_uninstall();
}

}  // namespace

extern "C" {

MOD_EXPORT ModResult mod_initialize(ModError* error) {
    twilit_hooks_install();
    twilit_config_install();
    settings_hub_install();
    for (size_t i = 0; i < std::size(kParts); ++i) {
        settings_hub_begin(kParts[i].name);
        const TwilitPartScope scope(static_cast<int>(i));
        if (const ModResult result = kParts[i].initialize(error); result != MOD_OK) {
            svc_log->error(mod_ctx, (std::string(kParts[i].name) + " failed to initialize").c_str());
            undo(i);
            return result;
        }
    }
    twilit_overlaps_init();
    settings_hub_init();
    svc_log->info(mod_ctx, "Twilit Dawn initialized (Essentials + Dawnlight + A Link Between Twilight)");
    return MOD_OK;
}

MOD_EXPORT ModResult mod_update(ModError* error) {
    ModResult result = MOD_OK;
    for (size_t i = 0; i < std::size(kParts); ++i) {
        const TwilitPartScope scope(static_cast<int>(i));
        if (const ModResult r = kParts[i].update(error); r != MOD_OK) result = r;
    }
    return result;
}

MOD_EXPORT ModResult mod_shutdown(ModError* error) {
    for (size_t i = std::size(kParts); i-- > 0;) {
        const TwilitPartScope scope(static_cast<int>(i));
        kParts[i].shutdown(error);
    }
    settings_hub_shutdown();
    twilit_config_uninstall();
    twilit_hooks_uninstall();
    return MOD_OK;
}

}  // extern "C"
